name: '1'
pos_emb_dim: 0
softmax_temp: 1
injection_info: [   # list of lists
  [6, 1, 3], # [InjectionLayer,NumStack,FilterSize,PadType] Start at 4 for ImageNet ResNet
  # [4, 1, 3],
  # [5, 1, 3],
  # [4, 1, 3],
  # [5, 1, 3]
]
padding: same
stride: 1
apply_stochastic_stride: False